# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node.
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Run cypress test
on:
  push:
    branches:
      - 'master'

jobs:
  cypress-test:
    name: Run on Chrome 83
    runs-on: ubuntu-latest
    container: cypress/browsers:node12.18.3-chrome87-ff82
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Install Cypress and verify
        run: 
            nmp ci
            $(npm nim)/cypress verify
        
      - name: Run Cypress tests
        run: nmp run test:chrome
        continue-on-error: false
        
