# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Run cypress test
on:
  push:
    branches:
      - 'main'

jobs:
  cypress-test:
    name: Run on Chrome 89
    runs-on: ubuntu-latest
    container: cypress/browsers:node14.17.0-chrome88-ff89
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Install Cypress and verify
        uses: cypress-io/github-action@v2
        with: 
          browser: chrome
        
